CREATE DATABASE ZEPTO;
USE ZEPTO

--SHOW ALL PRODUCTS
SELECT * FROM ZEPTO_V2;

--SHOW ONLY CATEGORY_NAME, MRP AND DISCOUNTED _SELLING_PRICE
SELECT NAME,MRP,DISCOUNTEDSELLINGPRICE FROM ZEPTO_V2;

--TOTAL NO OF PRODUCT
SELECT COUNT(NAME) FROM ZEPTO_V2;

--SHOW PRODUCT WHERE MRP IS GREATER THAN 100
SELECT NAME, MRP  FROM ZEPTO_V2 WHERE MRP >100;

--FIND PRODUCTS WITH DISCOUNBT GREATER THAN 20%
SELECT NAME ,DISCOUNTPERCENT FROM ZEPTO_V2 WHERE DISCOUNTPERCENT >20;

--SHOW PRODUCT WHERE QUANTITY IS 0
SELECT NAME,QUANTITY FROM ZEPTO_V2 WHERE QUANTITY =0;

-- FIND PRODUCTS WHERE DISCOUNTED PRICE IS LESS THAN 5000
SELECT NAME, DISCOUNTEDSELLINGPRICE FROM ZEPTO_V2 WHERE DISCOUNTEDSELLINGPRICE<5000;

--show products from a specific category
select category,name from zepto_v2 where category='cooking essentials';

--find products where weight is greater than 500gm
select name,weightingms from zepto_v2 where weightingms >500;

--show products sorted by mrp
select* from zepto_v2 order by mrp desc;

--sort by discount percentage 
select  * from zepto_v2 order by discountpercent asc;

--sort by available quantity descending
select * from zepto_v2 order by  availablequantity desc;

--show top 10 most expensive products
select top 10 * from zepto_v2 order by mrp desc;

--show top 5 highest discounted products
select top 5 * from zepto_v2 order by discountedsellingprice desc;

--find average mrp
select avg(mrp) AS AVERAGE_MRP FROM ZEPTO_V2;

--FIND MAXIMUM DISCOUNTED PRICE
SELECT MAX (DISCOUNTEDSELLINGPRICE) AS MAX_DISCOUNTED_SELLING_PRICE FROM ZEPTO_V2;

--FIND MINIMUM DISCOUNTED PRICE
SELECT MIN(DISCOUNTEDSELLINGPRICE) AS MIN_DISCOUNTED_SELLING_PRICE FROM ZEPTO_V2;

--COUNT PRODUCTS IN EACH CATEGORY
SELECT CATEGORY, COUNT(NAME) AS COUNT_CATEGORY FROM ZEPTO_V2 GROUP BY CATEGORY;

--FIND TOTAL AVAILABLE QUANTITYU PER CATEGORY
SELECT CATEGORY,SUM(QUANTITY) FROM ZEPTO_V2 GROUP BY CATEGORY;

--FIND AVERAGE DISCOUNT PERCENTAGE PER CATEGORY
SELECT CATEGORY ,AVG(DISCOUNTPERCENT) AS DISCOUNT_PERCENT_AVERAGE FROM ZEPTO_V2 GROUP BY CATEGORY;

--SHOW CATEGOPRIES WITH MORE THAN 150PRODUCTS
SELECT CATEGORY,COUNT(NAME) AS NAME_CATEGORY FROM ZEPTO_V2 GROUP BY CATEGORY HAVING COUNT(NAME)>150;

--FIND CATEGORIES WHERE AVERAGE DISCOUNT >8
SELECT CATEGORY,AVG(DISCOUNTPERCENT) AS AVG_DISCOUNT_PERCENT_CATEGORY FROM ZEPTO_V2 GROUP BY CATEGORY HAVING AVG(DISCOUNTPERCENT)>8;

--FIND CATEGORIES WHERE TOTAL AVAILABLE STOCK <500
SELECT CATEGORY,SUM(AVAILABLEQUANTITY) AS TOTAL_AVAILABLE_QUANTITY FROM ZEPTO_V2 GROUP BY CATEGORY HAVING SUM(AVAILABLEQUANTITY)<500;

--WHICH CATEGORY HAS HIGHEST AVERAGE MRP
SELECT TOP 1 CATEGORY, AVG(MRP) FROM ZEPTO_V2 GROUP BY CATEGORY;

--WHICH CATEGORY GIVES THE HIGHEST TOTAL DISOCUNT VALUE
SELECT TOP 1 CATEGORY, MAX(DISCOUNTEDSELLINGPRICE) AS HIGHEST_TOTAL_VALE FROM ZEPTO_V2 GROUP BY CATEGORY;

-- CREATE A COLUMN FROM DISCOUNT AMOUNT
SELECT *,DISCOUNTEDSELLINGPRICE AS DISCOUNT_AMOUNT  FROM ZEPTO_V2;

--CALCULATE PRICE PER GRAM 
SELECT *,CASE WHEN WEIGHTINGMS= 0 THEN NULL
ELSE DISCOUNTEDSELLINGPRICE/WEIGHTINGMS 
END AS PRICE_PER_GRAMS
FROM ZEPTO_V2;

--CALCULATE TOTAL STOCK VALUE 
SELECT *,(AVAILABLEQUANTITY *DISCOUNTEDSELLINGPRICE) AS TOTAL_STOCk_VALUE FROM ZEPTO_V2;

--POTENTIAL REVENUE PER CATEGORY
SELECT CATEGORY,SUM(AVAILABLEQUANTITY *DISCOUNTEDSELLINGPRICE)
AS POTENTIAL_REVENUE
FROM ZEPTO_V2
GROUP BY CATEGORY
ORDER BY POTENTIAL_REVENUE DESC;

---RANK PRODUCTS BY HIGHEST DISCOUNT BY ECH CATEGORY 
SELECT NAME,CATEGORY,DISCOUNTPERCENT,RANK()OVER(PARTITION BY CATEGORY
ORDER BY DISCOUNTPERCENT DESC) AS DISCOUNT_RANK FROM ZEPTO_V2;

--TOP3EXPENSIVE PRODUCT IN EACH CATEGORY 
select * from(
select name,category,mrp,rank()over(partition by category 
order by mrp desc) as price_rank from zepto_v2) t
where price_rank<=3;

--product with mrp higher than categroy average
select name, category,mrp from zepto_v2 z
where mrp>(select avg(mrp) from zepto_v2 where category= z.Personal Care);

--running total of stock value
SELECT *,(AVAILABLEQUANTITY *DISCOUNTEDSELLINGPRICE) AS TOTAL_STOCk_VALUE ,
sum(AVAILABLEQUANTITY *DISCOUNTEDSELLINGPRICE)
over (order by category 
rows between unbounded preceding and 
current row)
as running_total
from zepto_v2;

